package scripts.BerryPicker.gui;

import scripts.BerryPicker.ArchBerryPicker;
import scripts.BerryPicker.settings.EnumBerrySettings;
import scripts.BerryPicker.settings.Settings;

public class MainGUI extends javax.swing.JFrame {

	ArchBerryPicker scriptMain;
	
    /**
     * Creates new form GUI
     */
    public MainGUI(ArchBerryPicker scriptMain) {
    	this.scriptMain = scriptMain;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        berryPanel = new javax.swing.JPanel();
        berryOptions = new javax.swing.JComboBox();
        berryLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();

        
        setTitle("Arch Berry Picker");
        setAlwaysOnTop(true);

        berryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Berries to pick", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 102, 255))); // NOI18N

        berryOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cadava", "Redberry", "All" }));
        berryOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berryOptionsActionPerformed(evt);
            }
        });

        berryLabel.setText("Berries");

        javax.swing.GroupLayout berryPanelLayout = new javax.swing.GroupLayout(berryPanel);
        berryPanel.setLayout(berryPanelLayout);
        berryPanelLayout.setHorizontalGroup(
            berryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(berryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(berryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        berryPanelLayout.setVerticalGroup(
            berryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(berryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(berryLabel)
                    .addComponent(berryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(berryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(startButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(berryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>                        

    private void berryOptionsActionPerformed(java.awt.event.ActionEvent evt) {
    	
		switch (berryOptions.getSelectedItem().toString()) {
			case "Cadava":
				Settings.berriesToPick = EnumBerrySettings.CADAVA;
				break;
			case "Redberry":
				Settings.berriesToPick = EnumBerrySettings.REDBERRY;
				break;
			case "Both":
			default:
				Settings.berriesToPick = EnumBerrySettings.BOTH;
				break;
		}
    	
    	
    }    
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	this.setVisible(false);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel berryLabel;
    private javax.swing.JComboBox berryOptions;
    private javax.swing.JPanel berryPanel;
    private javax.swing.JButton startButton;
    // End of variables declaration                   
}
